targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/src/domain/models/**/*
            - lib/src/domain/models/*
            - lib/src/domain/failures/**/*
            - lib/src/domain/failures/*
      freezed:
        generate_for:
          include:
            - lib/src/presentation/**/**_state.dart
            - lib/src/domain/models/**/*
            - lib/src/domain/failures/**/*