name: jocaaguratv
description: Clean architecture in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  nested: ^1.0.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  extended_image: ^8.1.1
  url_strategy: ^0.2.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  slang: ^3.25.0
  slang_flutter: ^3.25.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  slang_build_runner: ^3.25.0

flutter:
  uses-material-design: true

  assets:
    - assets/
